#!/bin/zsh

FILES=(test0 test1 test2)

mkdir test0
chmod 715 test0
touch -t 202506012047 test0

touch test1
chmod 714 test1
echo -n 1234 > test1
touch -t 202506012146 test1

mkdir test2
chmod 504 test2
touch -t 202506012245 test2

tar -cf exo.tar "${FILES[@]}"
rm -rf $FILES "${FILES[@]}"
